#!/usr/bin/env bash
echo "Hello! I'm the marmot who runs the Dual Integration example application."

run() {
  cat <<EOF
Finally, we will move the dualintegrator service definition file
that was included in this repository to the ~/.eris/services dir
and then we will run [eris services start dualintegrator].

EOF
  cp ./dualintegrator.toml $HOME/.eris/services/.
  eris services start dualintegrator
  eris services logs dualintegrator -f
}

cleanup() {
  rm ./accounts.json &>/dev/null
  rm ./jobs_output.json &>/dev/null
  rm -rf ./abi &>/dev/null
  docker rmi dualintegrator &>/dev/null
  eris services rm dualintegrator --data --force --file &>/dev/null
  eris chains rm dualintegrator --data --force --dir &>/dev/null
}

main() {
  cleanup
  scripts/build
  if [ $? -ne 0 ]; then cleanup; exit 1; fi
  run
  trap "trap - SIGTERM; cleanup $@; kill -- -$$" SIGINT SIGTERM EXIT
  tail -f /dev/null & wait
}

main $@